### ISSUE TITLE
Suggested Logo

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#1]
![sehub](https://cloud.githubusercontent.com/assets/2984053/6825467/7c9d0402-d303-11e4-9827-62a6d66f937a.png)

**Comment by aranzaiger** [comment]
![image](https://cloud.githubusercontent.com/assets/4228830/6857618/cc96234a-d410-11e4-80b4-2cd7c0efaf11.png)
temp logo?
