### ISSUE TITLE
Project Page: Issues Tab: Clicking on User name will go to profile with wrong ID

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#106]
![screenshot from 2015-06-30 18-08-16](https://cloud.githubusercontent.com/assets/2984053/8434362/a559ae4e-1f53-11e5-9837-b00ce4f09ca2.png)

Clicking on the Name it will route to the profile page but with Github User ID and Not The SE-Hub User ID

**Comment by devMatan** [comment]
Fixed

**Comment by sagidayan** [comment]
good job!
make a pull request so ill see how that works.
