### ISSUE TITLE
getAllFutureTasks(tok, courseId)

### ISSUE THREAD

**Issue by devMatan** [sagidayan/SE-Hub#110]
In order to get 'courseId' (in the home page) i need to use - getAllCoursesByCampus(tok, campusId)
which means i need 'campusId' ==> getAllCampuses()
too many un-needed API calls.
Any Suggestions ?

**Comment by sagidayan** [comment]
don't understand what exactly is missing, and what do you want to do

**Comment by aranzaiger** [comment]
done
