### ISSUE TITLE
API: Remove User From Course/Campus/Project

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#125]
- [x] Course
 - [x] Campus
 - [x] Project

**Comment by aranzaiger** [comment]
already exists

**Comment by sagidayan** [comment]
@aranzaiger Cant find them in your Docs. push your changes (After making sure nothing broke :smile: )

**Comment by aranzaiger** [comment]
no changes made.
look under user api

**Comment by sagidayan** [comment]
Oh Ok, Ill check. Thanks!
