### ISSUE TITLE
API :getUserByToken with empty token returns 200 instead of 400

### ISSUE THREAD

**Issue by etyemy** [sagidayan/SE-Hub#24]
Steps to reproduce:
1. API call /api/getUserByToken/{empty token}

Problem: call returns 200 
Expected: return 400

**Comment by sagidayan** [comment]
@aranzaiger, maybe 204 as well?

**Comment by aranzaiger** [comment]
its a different issue.. i dont know where the code goes to. it wont go to "getUserByToken".
response code is 200 but page returning is 404

**Comment by etyemy** [comment]
Im still getting 200.

**Comment by sagidayan** [comment]
@aranzaiger ill look in to it. moving the bug to me

**Comment by sagidayan** [comment]
Fixed

**Comment by etyemy** [comment]
great!
