### ISSUE TITLE
API :getUserByToken with invalid token returns 400 instead of 403

### ISSUE THREAD

**Issue by etyemy** [sagidayan/SE-Hub#25]
Steps to reproduce:
1. API call /api/getUserByToken/{invalid token}

Problem: call returns 400
Expected: return 403

**Comment by aranzaiger** [comment]
fixed

**Comment by aranzaiger** [comment]
dont think its 403, and maybe not even 400.
403 is forbidden. we dont request for somthing we're not allowed to ask for.
400 is bad request. our request is not necessarilybad.

we might just not have that user. and the server can return 200 - no user found.. i think..
or maybe a different code

**Comment by sagidayan** [comment]
Make sense. Maby 204 ?
See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes the 2xx family

**Comment by aranzaiger** [comment]
lets do somthing in the middle? 202?

yea i think either 200 or 204 make sense

**Comment by sagidayan** [comment]
Okay so lets try to be as formal as possible in the API - 204 it is... @aranzaiger & @etyemy please fix it in your code. and in commit message add the tag #25

**Comment by etyemy** [comment]
I put 204

**Comment by sagidayan** [comment]
Let me know when this issue is closed. Both API and Unit test.

Please add to the commit message the tag #25. So it will show ul here
