### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#3]
A link to the task: [Click Here](http://jce-il.github.io/se-class/project/se-proj01-idea.pdf)

**Comment by sagidayan** [comment]
@aranzaiger Please work on the SOW. see the link that is included in the issue description.

**Comment by devMatan** [comment]
Link to the Presentation ===> :+1: 
https://drive.google.com/open?id=0B1VLHX6HWo9mVm9GWHdpTWJCMWc&authuser=0

You will be asked to request for privilege.

**Comment by sagidayan** [comment]
:+1:
