### ISSUE TITLE
Task Creator + Task Preview

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#35]
Need to implement a task page (to create a task) + an option for the lecturer to preview the task

**Comment by sagidayan** [comment]
need some feedback on it... thanks.

**Comment by sagidayan** [comment]
@aranzaiger @etyemy @devMatan Any Suggestions?!

/tasks/new

**Comment by etyemy** [comment]
I would put all the fields one on top the the other, other than that Ill
think of other suggestions


2015-06-23 20:59 GMT+03:00 Sagi Dayan <notifications@github.com>:

**Comment by sagidayan** [comment]
what fields? there are 3 sections there. every section is different. and needs his own space.

please be more specific

**Comment by etyemy** [comment]
Keep the task preview on the right.
Add a component could be under the task info. Both should have frames like
the task preview.
The page could be more simetric, here look at what i had in mind.[image:
תמונה מוטבעת 1]


2015-06-23 22:03 GMT+03:00 Sagi Dayan <notifications@github.com>:

**Comment by sagidayan** [comment]
Cant see the image. Post it via github. And not the mail

**Comment by etyemy** [comment]
https://github.com/sagidayan/SE-Hub/issues/64

2015-06-23 22:23 GMT+03:00 Sagi Dayan <notifications@github.com>:
