### ISSUE TITLE
Technology Stack 

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#4]
We need to decide  what technologies we will relay on ... this issue is marked as an open discussion.

**Comment by sagidayan** [comment]
lets use for the back-end Google-App-Engine  + Python + Google-cloud-storage
as this is what our teacher wants.

and for the front-end stuff AngularJS+Material-Design-For-Angular that way we could develop rapidly.

:wink:

Other suggestions?

**Comment by aranzaiger** [comment]
rapidllllllly! hohoho

**Comment by sagidayan** [comment]
back-end Python with Flask -> [Click here](http://flask.pocoo.org/) for more details

**Comment by sagidayan** [comment]
Final:
**Back-end:** GAE + Python + Flask + Github API (OAuth)
 **Front-end:** AngularJS + Material Design
