### ISSUE TITLE
need delete API functions

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#46]
- [x] campuses
 - [x] classes
 - [x] courses
 - [x] user from campuses or courses

**Comment by aranzaiger** [comment]
on the way

**Comment by etyemy** [comment]
yea I need them for every test. Thanks Sagi

2015-06-18 21:19 GMT+03:00 Aran Zaiger <notifications@github.com>:

**Comment by aranzaiger** [comment]
classes == courses
also delete project added
user from campuses or courses is next. i'll need to implamant a list of users in courses/campuses or the oppesite

**Comment by aranzaiger** [comment]
who can delete user from course or campus? user itself and owner lecturer?
if not self delete (lecturer to other student), by what parameter? we dont have SeToken/userId exposed

**Comment by sagidayan** [comment]
if a lecturer wants to delete a user (234)  from campus (123) he will call the API at
/api/campus/deleteUser/234/123

or something like that

**Comment by aranzaiger** [comment]
What about token?

**Comment by sagidayan** [comment]
/api/campus/deleteUser/lecturerToken/234/123
