### ISSUE TITLE
Fixing Doc

### ISSUE THREAD

**Issue by aranzaiger** [sagidayan/SE-Hub#54]
@sagidayan @devMatan @etyemy pls let me know (open bugs or here) about API Documenation issues u find. i.e 'startDate': '2015-14-3' instead of 
"dueDate":{
"year":2010,
 "month":2,
 "day":4
 }

or any other dumb mistakes

**Comment by sagidayan** [comment]
:+1:

**Comment by sagidayan** [comment]
@aranzaiger needs a lot of love... 
the API docs are out dated
