### ISSUE TITLE
On First Registration Page - Clicking Submit: wont update user data

### ISSUE THREAD

**Issue by sagidayan** [sagidayan/SE-Hub#63]
Steps to reproduce:
 1. make sure your user is set to first login
 2. login 
 3. fill your name
 4. check that you are a lecturer
 5. click submit

**Problem:** User Is not being updated in DB.

@devMatan Make Sure:
- [x] you are making an API call for UpdateUser and that you are sending the right data.
- [x] The Name Textbox is Mandatory. clicking on SUBMIT with an empty Name or no Campus will show a dialog message with the error.

**Comment by devMatan** [comment]
Fixed
