### ISSUE TITLE
[SE-Hub] Task Creator + Task Preview (#35)‏ suggestion

### ISSUE THREAD

**Issue by etyemy** [sagidayan/SE-Hub#64]
![idea](https://cloud.githubusercontent.com/assets/11498626/8315189/6d7474e8-19f7-11e5-91f6-4df525250531.png)

**Comment by sagidayan** [comment]
@aranzaiger what do you think?

**Comment by aranzaiger** [comment]
looks nice

**Comment by sagidayan** [comment]
ok will do.

**Comment by sagidayan** [comment]
Done!
